### PR TITLE
Fixes to allow successful merges to deploy

### LINKED ISSUE #1: Doesn't work when PR mergeable_state = clean
Hello,

I've tried to set up this up for my own repos but it fails every time on a simple pull request with the error
```
Error: Deployment failed: PR can't be cleanly merged with base branch.
```

I have tried both a PR that could be `merge --fast-forward` and a PR that needs a merge commit and got the same error.

I've enabled debug logging in my test repo and saw that the pull request payload that Github returned contained this state
```
 "mergeable_state": "clean"
```

As  far as I could tell from the code in `entrypoint.py` this state isn't handled.
https://github.com/alexjurkiewicz/pr-comment-github-deployment/blob/master/entrypoint.py#L156-L176

### PR DESCRIPTION
**Pull request by pazaan**
* Update `validate_pr` to handle additional states
* Update `check_commit` to handle additional states
* Fixes #1

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
Do you have an example of this PR working in a public repository?

**Comment by pazaan** [comment]
Yep. Test repo is [here](https://github.com/pazaan/gittest).
PR where all the testing happened (including all the debugging) is [here](https://github.com/pazaan/gittest/pull/5).

**Comment by alexjurkiewicz** [comment]
thank you! I will copy your example workflow to this repo

**Comment by pazaan** [comment]
Great! Though in that case, please make sure to credit [@sanderknape](https://github.com/SanderKnape). I based my test workflow from [the one in his repo](https://github.com/SanderKnape/pr-deployments/blob/master/.github/workflows/pr-deployment.yaml).

**Pull request merged**
